const state = {
  items: [],
  selectedId: null,
  activeTag: "all",
  searchQuery: "",
  sourceFilter: "all",
  folderFilter: "all",
  favoriteFilter: "all",
  modelFilter: "all",
  sortOrder: "newest",
  editorOpen: false,
  viewerOpen: false,
  draftObjectUrl: "",
  draftBlob: null,
  draftMetadata: null,
  draftVersion: 0,
  isInitialized: false,
  libraryRoots: [],
  isDraggingFiles: false,
};

